const sgoviI18n = {
    de: {
        noSsl: "Kein SSL",
        indexing: "WIRD INDEXIERT",
        waiting: "WARTET",
        found: "BEKANNT",
        notFound: "UNBEKANNT",
        add: "Hinzufügen",
        loading: "Lädt...",
        success: "Erfolg!",
        error: "Fehler",
        bulkConfirm: "Domains zur Warteschlange hinzufügen?",
        bulkSuccess: "Domains wurden übermittelt.",
        noDomains: "Keine Domains gefunden.",
        popupTitle: "Website Checker",
        scanBtn: "Seite scannen"
    },
    en: {
        noSsl: "No SSL",
        indexing: "INDEXING",
        waiting: "WAITING",
        found: "KNOWN",
        notFound: "UNKNOWN",
        add: "Add",
        loading: "Loading...",
        success: "Success!",
        error: "Error",
        bulkConfirm: "Add domains to queue?",
        bulkSuccess: "Domains submitted.",
        noDomains: "No domains found.",
        popupTitle: "Website Checker",
        scanBtn: "Scan Page"
    },
    it: {
        noSsl: "No SSL",
        indexing: "INDICIZZAZIONE",
        waiting: "IN ATTESA",
        found: "CONOSCIUTO",
        notFound: "SCONOSCIUTO",
        add: "Aggiungi",
        loading: "Caricamento...",
        success: "Successo!",
        error: "Errore",
        bulkConfirm: "Aggiungere domini alla coda?",
        bulkSuccess: "Domini inviati.",
        noDomains: "Nessun dominio trovato.",
        popupTitle: "Controllo Sito",
        scanBtn: "Scansiona pagina"
    },
    fr: {
        noSsl: "Pas de SSL",
        indexing: "INDEXATION",
        waiting: "EN ATTENTE",
        found: "CONNU",
        notFound: "INCONNU",
        add: "Ajouter",
        loading: "Chargement...",
        success: "Succès!",
        error: "Erreur",
        bulkConfirm: "Ajouter les domaines à la file?",
        bulkSuccess: "Domaines envoyés.",
        noDomains: "Aucun domaine trouvé.",
        popupTitle: "Vérificateur de site",
        scanBtn: "Scanner la page"
    },
    es: {
        noSsl: "Sin SSL",
        indexing: "INDEXANDO",
        waiting: "ESPERANDO",
        found: "CONOCIDO",
        notFound: "DESCONOCIDO",
        add: "Añadir",
        loading: "Cargando...",
        success: "¡Éxito!",
        error: "Error",
        bulkConfirm: "¿Añadir dominios a la cola?",
        bulkSuccess: "Dominios enviados.",
        noDomains: "No se encontraron dominios.",
        popupTitle: "Checker de sitios",
        scanBtn: "Escanear página"
    },
    nl: {
        noSsl: "Geen SSL",
        indexing: "INDEXEREN",
        waiting: "WACHTEN",
        found: "BEKEND",
        notFound: "ONBEKEND",
        add: "Toevoegen",
        loading: "Laden...",
        success: "Succes!",
        error: "Fout",
        bulkConfirm: "Domeinen aan wachtrij toevoegen?",
        bulkSuccess: "Domeinen ingediend.",
        noDomains: "Geen domeinen gevonden.",
        popupTitle: "Website Checker",
        scanBtn: "Pagina scannen"
    }
};